// Generated by gencpp from file cpswarm_msgs/ClearOfObstacles.msg
// DO NOT EDIT!


#ifndef CPSWARM_MSGS_MESSAGE_CLEAROFOBSTACLES_H
#define CPSWARM_MSGS_MESSAGE_CLEAROFOBSTACLES_H

#include <ros/service_traits.h>


#include <cpswarm_msgs/ClearOfObstaclesRequest.h>
#include <cpswarm_msgs/ClearOfObstaclesResponse.h>


namespace cpswarm_msgs
{

struct ClearOfObstacles
{

typedef ClearOfObstaclesRequest Request;
typedef ClearOfObstaclesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClearOfObstacles
} // namespace cpswarm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cpswarm_msgs::ClearOfObstacles > {
  static const char* value()
  {
    return "0f13874ec47789a29a9f87f75379435d";
  }

  static const char* value(const ::cpswarm_msgs::ClearOfObstacles&) { return value(); }
};

template<>
struct DataType< ::cpswarm_msgs::ClearOfObstacles > {
  static const char* value()
  {
    return "cpswarm_msgs/ClearOfObstacles";
  }

  static const char* value(const ::cpswarm_msgs::ClearOfObstacles&) { return value(); }
};


// service_traits::MD5Sum< ::cpswarm_msgs::ClearOfObstaclesRequest> should match 
// service_traits::MD5Sum< ::cpswarm_msgs::ClearOfObstacles > 
template<>
struct MD5Sum< ::cpswarm_msgs::ClearOfObstaclesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cpswarm_msgs::ClearOfObstacles >::value();
  }
  static const char* value(const ::cpswarm_msgs::ClearOfObstaclesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpswarm_msgs::ClearOfObstaclesRequest> should match 
// service_traits::DataType< ::cpswarm_msgs::ClearOfObstacles > 
template<>
struct DataType< ::cpswarm_msgs::ClearOfObstaclesRequest>
{
  static const char* value()
  {
    return DataType< ::cpswarm_msgs::ClearOfObstacles >::value();
  }
  static const char* value(const ::cpswarm_msgs::ClearOfObstaclesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cpswarm_msgs::ClearOfObstaclesResponse> should match 
// service_traits::MD5Sum< ::cpswarm_msgs::ClearOfObstacles > 
template<>
struct MD5Sum< ::cpswarm_msgs::ClearOfObstaclesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cpswarm_msgs::ClearOfObstacles >::value();
  }
  static const char* value(const ::cpswarm_msgs::ClearOfObstaclesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpswarm_msgs::ClearOfObstaclesResponse> should match 
// service_traits::DataType< ::cpswarm_msgs::ClearOfObstacles > 
template<>
struct DataType< ::cpswarm_msgs::ClearOfObstaclesResponse>
{
  static const char* value()
  {
    return DataType< ::cpswarm_msgs::ClearOfObstacles >::value();
  }
  static const char* value(const ::cpswarm_msgs::ClearOfObstaclesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CPSWARM_MSGS_MESSAGE_CLEAROFOBSTACLES_H
