// Generated by gencpp from file cpswarm_msgs/DangerResponse.msg
// DO NOT EDIT!


#ifndef CPSWARM_MSGS_MESSAGE_DANGERRESPONSE_H
#define CPSWARM_MSGS_MESSAGE_DANGERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cpswarm_msgs
{
template <class ContainerAllocator>
struct DangerResponse_
{
  typedef DangerResponse_<ContainerAllocator> Type;

  DangerResponse_()
    : danger(false)
    , backoff(0.0)
    , direction(0.0)  {
    }
  DangerResponse_(const ContainerAllocator& _alloc)
    : danger(false)
    , backoff(0.0)
    , direction(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _danger_type;
  _danger_type danger;

   typedef double _backoff_type;
  _backoff_type backoff;

   typedef double _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::cpswarm_msgs::DangerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cpswarm_msgs::DangerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DangerResponse_

typedef ::cpswarm_msgs::DangerResponse_<std::allocator<void> > DangerResponse;

typedef boost::shared_ptr< ::cpswarm_msgs::DangerResponse > DangerResponsePtr;
typedef boost::shared_ptr< ::cpswarm_msgs::DangerResponse const> DangerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cpswarm_msgs::DangerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cpswarm_msgs::DangerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cpswarm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'swarmros': ['/opt/ros/kinetic/share/swarmros/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'cpswarm_msgs': ['/home/miguel/ws/cpswarm_server/src/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/devel/.private/cpswarm_msgs/share/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/src/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/devel/.private/cpswarm_msgs/share/cpswarm_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cpswarm_msgs::DangerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpswarm_msgs::DangerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpswarm_msgs::DangerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpswarm_msgs::DangerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpswarm_msgs::DangerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpswarm_msgs::DangerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cpswarm_msgs::DangerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ce2958a2ab9de30c0653c98ced6972cd";
  }

  static const char* value(const ::cpswarm_msgs::DangerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xce2958a2ab9de30cULL;
  static const uint64_t static_value2 = 0x0653c98ced6972cdULL;
};

template<class ContainerAllocator>
struct DataType< ::cpswarm_msgs::DangerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cpswarm_msgs/DangerResponse";
  }

  static const char* value(const ::cpswarm_msgs::DangerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cpswarm_msgs::DangerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool danger\n\
float64 backoff\n\
float64 direction\n\
\n\
";
  }

  static const char* value(const ::cpswarm_msgs::DangerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cpswarm_msgs::DangerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.danger);
      stream.next(m.backoff);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DangerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cpswarm_msgs::DangerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cpswarm_msgs::DangerResponse_<ContainerAllocator>& v)
  {
    s << indent << "danger: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.danger);
    s << indent << "backoff: ";
    Printer<double>::stream(s, indent + "  ", v.backoff);
    s << indent << "direction: ";
    Printer<double>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CPSWARM_MSGS_MESSAGE_DANGERRESPONSE_H
