// Generated by gencpp from file cpswarm_msgs/FixToPose.msg
// DO NOT EDIT!


#ifndef CPSWARM_MSGS_MESSAGE_FIXTOPOSE_H
#define CPSWARM_MSGS_MESSAGE_FIXTOPOSE_H

#include <ros/service_traits.h>


#include <cpswarm_msgs/FixToPoseRequest.h>
#include <cpswarm_msgs/FixToPoseResponse.h>


namespace cpswarm_msgs
{

struct FixToPose
{

typedef FixToPoseRequest Request;
typedef FixToPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FixToPose
} // namespace cpswarm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cpswarm_msgs::FixToPose > {
  static const char* value()
  {
    return "9600713b46c16732c110696731a4bfe8";
  }

  static const char* value(const ::cpswarm_msgs::FixToPose&) { return value(); }
};

template<>
struct DataType< ::cpswarm_msgs::FixToPose > {
  static const char* value()
  {
    return "cpswarm_msgs/FixToPose";
  }

  static const char* value(const ::cpswarm_msgs::FixToPose&) { return value(); }
};


// service_traits::MD5Sum< ::cpswarm_msgs::FixToPoseRequest> should match 
// service_traits::MD5Sum< ::cpswarm_msgs::FixToPose > 
template<>
struct MD5Sum< ::cpswarm_msgs::FixToPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cpswarm_msgs::FixToPose >::value();
  }
  static const char* value(const ::cpswarm_msgs::FixToPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpswarm_msgs::FixToPoseRequest> should match 
// service_traits::DataType< ::cpswarm_msgs::FixToPose > 
template<>
struct DataType< ::cpswarm_msgs::FixToPoseRequest>
{
  static const char* value()
  {
    return DataType< ::cpswarm_msgs::FixToPose >::value();
  }
  static const char* value(const ::cpswarm_msgs::FixToPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cpswarm_msgs::FixToPoseResponse> should match 
// service_traits::MD5Sum< ::cpswarm_msgs::FixToPose > 
template<>
struct MD5Sum< ::cpswarm_msgs::FixToPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cpswarm_msgs::FixToPose >::value();
  }
  static const char* value(const ::cpswarm_msgs::FixToPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpswarm_msgs::FixToPoseResponse> should match 
// service_traits::DataType< ::cpswarm_msgs::FixToPose > 
template<>
struct DataType< ::cpswarm_msgs::FixToPoseResponse>
{
  static const char* value()
  {
    return DataType< ::cpswarm_msgs::FixToPose >::value();
  }
  static const char* value(const ::cpswarm_msgs::FixToPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CPSWARM_MSGS_MESSAGE_FIXTOPOSE_H
