// Generated by gencpp from file cpswarm_msgs/GetDouble.msg
// DO NOT EDIT!


#ifndef CPSWARM_MSGS_MESSAGE_GETDOUBLE_H
#define CPSWARM_MSGS_MESSAGE_GETDOUBLE_H

#include <ros/service_traits.h>


#include <cpswarm_msgs/GetDoubleRequest.h>
#include <cpswarm_msgs/GetDoubleResponse.h>


namespace cpswarm_msgs
{

struct GetDouble
{

typedef GetDoubleRequest Request;
typedef GetDoubleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDouble
} // namespace cpswarm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cpswarm_msgs::GetDouble > {
  static const char* value()
  {
    return "1b1594d2b74931ef8fe7be8e2d594455";
  }

  static const char* value(const ::cpswarm_msgs::GetDouble&) { return value(); }
};

template<>
struct DataType< ::cpswarm_msgs::GetDouble > {
  static const char* value()
  {
    return "cpswarm_msgs/GetDouble";
  }

  static const char* value(const ::cpswarm_msgs::GetDouble&) { return value(); }
};


// service_traits::MD5Sum< ::cpswarm_msgs::GetDoubleRequest> should match 
// service_traits::MD5Sum< ::cpswarm_msgs::GetDouble > 
template<>
struct MD5Sum< ::cpswarm_msgs::GetDoubleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cpswarm_msgs::GetDouble >::value();
  }
  static const char* value(const ::cpswarm_msgs::GetDoubleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpswarm_msgs::GetDoubleRequest> should match 
// service_traits::DataType< ::cpswarm_msgs::GetDouble > 
template<>
struct DataType< ::cpswarm_msgs::GetDoubleRequest>
{
  static const char* value()
  {
    return DataType< ::cpswarm_msgs::GetDouble >::value();
  }
  static const char* value(const ::cpswarm_msgs::GetDoubleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cpswarm_msgs::GetDoubleResponse> should match 
// service_traits::MD5Sum< ::cpswarm_msgs::GetDouble > 
template<>
struct MD5Sum< ::cpswarm_msgs::GetDoubleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cpswarm_msgs::GetDouble >::value();
  }
  static const char* value(const ::cpswarm_msgs::GetDoubleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpswarm_msgs::GetDoubleResponse> should match 
// service_traits::DataType< ::cpswarm_msgs::GetDouble > 
template<>
struct DataType< ::cpswarm_msgs::GetDoubleResponse>
{
  static const char* value()
  {
    return DataType< ::cpswarm_msgs::GetDouble >::value();
  }
  static const char* value(const ::cpswarm_msgs::GetDoubleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CPSWARM_MSGS_MESSAGE_GETDOUBLE_H
