// Generated by gencpp from file cpswarm_msgs/GetPoint.msg
// DO NOT EDIT!


#ifndef CPSWARM_MSGS_MESSAGE_GETPOINT_H
#define CPSWARM_MSGS_MESSAGE_GETPOINT_H

#include <ros/service_traits.h>


#include <cpswarm_msgs/GetPointRequest.h>
#include <cpswarm_msgs/GetPointResponse.h>


namespace cpswarm_msgs
{

struct GetPoint
{

typedef GetPointRequest Request;
typedef GetPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPoint
} // namespace cpswarm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cpswarm_msgs::GetPoint > {
  static const char* value()
  {
    return "a7c84ff13976aa04656e56e300124444";
  }

  static const char* value(const ::cpswarm_msgs::GetPoint&) { return value(); }
};

template<>
struct DataType< ::cpswarm_msgs::GetPoint > {
  static const char* value()
  {
    return "cpswarm_msgs/GetPoint";
  }

  static const char* value(const ::cpswarm_msgs::GetPoint&) { return value(); }
};


// service_traits::MD5Sum< ::cpswarm_msgs::GetPointRequest> should match 
// service_traits::MD5Sum< ::cpswarm_msgs::GetPoint > 
template<>
struct MD5Sum< ::cpswarm_msgs::GetPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cpswarm_msgs::GetPoint >::value();
  }
  static const char* value(const ::cpswarm_msgs::GetPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpswarm_msgs::GetPointRequest> should match 
// service_traits::DataType< ::cpswarm_msgs::GetPoint > 
template<>
struct DataType< ::cpswarm_msgs::GetPointRequest>
{
  static const char* value()
  {
    return DataType< ::cpswarm_msgs::GetPoint >::value();
  }
  static const char* value(const ::cpswarm_msgs::GetPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cpswarm_msgs::GetPointResponse> should match 
// service_traits::MD5Sum< ::cpswarm_msgs::GetPoint > 
template<>
struct MD5Sum< ::cpswarm_msgs::GetPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cpswarm_msgs::GetPoint >::value();
  }
  static const char* value(const ::cpswarm_msgs::GetPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpswarm_msgs::GetPointResponse> should match 
// service_traits::DataType< ::cpswarm_msgs::GetPoint > 
template<>
struct DataType< ::cpswarm_msgs::GetPointResponse>
{
  static const char* value()
  {
    return DataType< ::cpswarm_msgs::GetPoint >::value();
  }
  static const char* value(const ::cpswarm_msgs::GetPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CPSWARM_MSGS_MESSAGE_GETPOINT_H
