// Generated by gencpp from file cpswarm_msgs/GetPoints.msg
// DO NOT EDIT!


#ifndef CPSWARM_MSGS_MESSAGE_GETPOINTS_H
#define CPSWARM_MSGS_MESSAGE_GETPOINTS_H

#include <ros/service_traits.h>


#include <cpswarm_msgs/GetPointsRequest.h>
#include <cpswarm_msgs/GetPointsResponse.h>


namespace cpswarm_msgs
{

struct GetPoints
{

typedef GetPointsRequest Request;
typedef GetPointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPoints
} // namespace cpswarm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cpswarm_msgs::GetPoints > {
  static const char* value()
  {
    return "3fb3f9dacc279b964c4c8341122c34df";
  }

  static const char* value(const ::cpswarm_msgs::GetPoints&) { return value(); }
};

template<>
struct DataType< ::cpswarm_msgs::GetPoints > {
  static const char* value()
  {
    return "cpswarm_msgs/GetPoints";
  }

  static const char* value(const ::cpswarm_msgs::GetPoints&) { return value(); }
};


// service_traits::MD5Sum< ::cpswarm_msgs::GetPointsRequest> should match 
// service_traits::MD5Sum< ::cpswarm_msgs::GetPoints > 
template<>
struct MD5Sum< ::cpswarm_msgs::GetPointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cpswarm_msgs::GetPoints >::value();
  }
  static const char* value(const ::cpswarm_msgs::GetPointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpswarm_msgs::GetPointsRequest> should match 
// service_traits::DataType< ::cpswarm_msgs::GetPoints > 
template<>
struct DataType< ::cpswarm_msgs::GetPointsRequest>
{
  static const char* value()
  {
    return DataType< ::cpswarm_msgs::GetPoints >::value();
  }
  static const char* value(const ::cpswarm_msgs::GetPointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cpswarm_msgs::GetPointsResponse> should match 
// service_traits::MD5Sum< ::cpswarm_msgs::GetPoints > 
template<>
struct MD5Sum< ::cpswarm_msgs::GetPointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cpswarm_msgs::GetPoints >::value();
  }
  static const char* value(const ::cpswarm_msgs::GetPointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpswarm_msgs::GetPointsResponse> should match 
// service_traits::DataType< ::cpswarm_msgs::GetPoints > 
template<>
struct DataType< ::cpswarm_msgs::GetPointsResponse>
{
  static const char* value()
  {
    return DataType< ::cpswarm_msgs::GetPoints >::value();
  }
  static const char* value(const ::cpswarm_msgs::GetPointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CPSWARM_MSGS_MESSAGE_GETPOINTS_H
