// Generated by gencpp from file cpswarm_msgs/GetSector.msg
// DO NOT EDIT!


#ifndef CPSWARM_MSGS_MESSAGE_GETSECTOR_H
#define CPSWARM_MSGS_MESSAGE_GETSECTOR_H

#include <ros/service_traits.h>


#include <cpswarm_msgs/GetSectorRequest.h>
#include <cpswarm_msgs/GetSectorResponse.h>


namespace cpswarm_msgs
{

struct GetSector
{

typedef GetSectorRequest Request;
typedef GetSectorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSector
} // namespace cpswarm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cpswarm_msgs::GetSector > {
  static const char* value()
  {
    return "32e1c0b6f254bb48e963512143e9aa6f";
  }

  static const char* value(const ::cpswarm_msgs::GetSector&) { return value(); }
};

template<>
struct DataType< ::cpswarm_msgs::GetSector > {
  static const char* value()
  {
    return "cpswarm_msgs/GetSector";
  }

  static const char* value(const ::cpswarm_msgs::GetSector&) { return value(); }
};


// service_traits::MD5Sum< ::cpswarm_msgs::GetSectorRequest> should match 
// service_traits::MD5Sum< ::cpswarm_msgs::GetSector > 
template<>
struct MD5Sum< ::cpswarm_msgs::GetSectorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cpswarm_msgs::GetSector >::value();
  }
  static const char* value(const ::cpswarm_msgs::GetSectorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpswarm_msgs::GetSectorRequest> should match 
// service_traits::DataType< ::cpswarm_msgs::GetSector > 
template<>
struct DataType< ::cpswarm_msgs::GetSectorRequest>
{
  static const char* value()
  {
    return DataType< ::cpswarm_msgs::GetSector >::value();
  }
  static const char* value(const ::cpswarm_msgs::GetSectorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cpswarm_msgs::GetSectorResponse> should match 
// service_traits::MD5Sum< ::cpswarm_msgs::GetSector > 
template<>
struct MD5Sum< ::cpswarm_msgs::GetSectorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cpswarm_msgs::GetSector >::value();
  }
  static const char* value(const ::cpswarm_msgs::GetSectorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpswarm_msgs::GetSectorResponse> should match 
// service_traits::DataType< ::cpswarm_msgs::GetSector > 
template<>
struct DataType< ::cpswarm_msgs::GetSectorResponse>
{
  static const char* value()
  {
    return DataType< ::cpswarm_msgs::GetSector >::value();
  }
  static const char* value(const ::cpswarm_msgs::GetSectorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CPSWARM_MSGS_MESSAGE_GETSECTOR_H
