// Generated by gencpp from file cpswarm_msgs/GetWaypointResponse.msg
// DO NOT EDIT!


#ifndef CPSWARM_MSGS_MESSAGE_GETWAYPOINTRESPONSE_H
#define CPSWARM_MSGS_MESSAGE_GETWAYPOINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace cpswarm_msgs
{
template <class ContainerAllocator>
struct GetWaypointResponse_
{
  typedef GetWaypointResponse_<ContainerAllocator> Type;

  GetWaypointResponse_()
    : point()
    , valid(false)  {
    }
  GetWaypointResponse_(const ContainerAllocator& _alloc)
    : point(_alloc)
    , valid(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;

   typedef uint8_t _valid_type;
  _valid_type valid;





  typedef boost::shared_ptr< ::cpswarm_msgs::GetWaypointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cpswarm_msgs::GetWaypointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetWaypointResponse_

typedef ::cpswarm_msgs::GetWaypointResponse_<std::allocator<void> > GetWaypointResponse;

typedef boost::shared_ptr< ::cpswarm_msgs::GetWaypointResponse > GetWaypointResponsePtr;
typedef boost::shared_ptr< ::cpswarm_msgs::GetWaypointResponse const> GetWaypointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cpswarm_msgs::GetWaypointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cpswarm_msgs::GetWaypointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cpswarm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'swarmros': ['/opt/ros/kinetic/share/swarmros/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'cpswarm_msgs': ['/home/miguel/ws/cpswarm_server/src/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/devel/.private/cpswarm_msgs/share/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/src/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/devel/.private/cpswarm_msgs/share/cpswarm_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cpswarm_msgs::GetWaypointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpswarm_msgs::GetWaypointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpswarm_msgs::GetWaypointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpswarm_msgs::GetWaypointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpswarm_msgs::GetWaypointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpswarm_msgs::GetWaypointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cpswarm_msgs::GetWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f30b12797aafe4fbdd7bd946083c2bbd";
  }

  static const char* value(const ::cpswarm_msgs::GetWaypointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf30b12797aafe4fbULL;
  static const uint64_t static_value2 = 0xdd7bd946083c2bbdULL;
};

template<class ContainerAllocator>
struct DataType< ::cpswarm_msgs::GetWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cpswarm_msgs/GetWaypointResponse";
  }

  static const char* value(const ::cpswarm_msgs::GetWaypointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cpswarm_msgs::GetWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point point\n\
bool valid\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::cpswarm_msgs::GetWaypointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cpswarm_msgs::GetWaypointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point);
      stream.next(m.valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetWaypointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cpswarm_msgs::GetWaypointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cpswarm_msgs::GetWaypointResponse_<ContainerAllocator>& v)
  {
    s << indent << "point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CPSWARM_MSGS_MESSAGE_GETWAYPOINTRESPONSE_H
