// Generated by gencpp from file cpswarm_msgs/GetWaypoint.msg
// DO NOT EDIT!


#ifndef CPSWARM_MSGS_MESSAGE_GETWAYPOINT_H
#define CPSWARM_MSGS_MESSAGE_GETWAYPOINT_H

#include <ros/service_traits.h>


#include <cpswarm_msgs/GetWaypointRequest.h>
#include <cpswarm_msgs/GetWaypointResponse.h>


namespace cpswarm_msgs
{

struct GetWaypoint
{

typedef GetWaypointRequest Request;
typedef GetWaypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetWaypoint
} // namespace cpswarm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cpswarm_msgs::GetWaypoint > {
  static const char* value()
  {
    return "60903162a9fb13eb0253b5b0ab0c0cd4";
  }

  static const char* value(const ::cpswarm_msgs::GetWaypoint&) { return value(); }
};

template<>
struct DataType< ::cpswarm_msgs::GetWaypoint > {
  static const char* value()
  {
    return "cpswarm_msgs/GetWaypoint";
  }

  static const char* value(const ::cpswarm_msgs::GetWaypoint&) { return value(); }
};


// service_traits::MD5Sum< ::cpswarm_msgs::GetWaypointRequest> should match 
// service_traits::MD5Sum< ::cpswarm_msgs::GetWaypoint > 
template<>
struct MD5Sum< ::cpswarm_msgs::GetWaypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cpswarm_msgs::GetWaypoint >::value();
  }
  static const char* value(const ::cpswarm_msgs::GetWaypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpswarm_msgs::GetWaypointRequest> should match 
// service_traits::DataType< ::cpswarm_msgs::GetWaypoint > 
template<>
struct DataType< ::cpswarm_msgs::GetWaypointRequest>
{
  static const char* value()
  {
    return DataType< ::cpswarm_msgs::GetWaypoint >::value();
  }
  static const char* value(const ::cpswarm_msgs::GetWaypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cpswarm_msgs::GetWaypointResponse> should match 
// service_traits::MD5Sum< ::cpswarm_msgs::GetWaypoint > 
template<>
struct MD5Sum< ::cpswarm_msgs::GetWaypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cpswarm_msgs::GetWaypoint >::value();
  }
  static const char* value(const ::cpswarm_msgs::GetWaypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpswarm_msgs::GetWaypointResponse> should match 
// service_traits::DataType< ::cpswarm_msgs::GetWaypoint > 
template<>
struct DataType< ::cpswarm_msgs::GetWaypointResponse>
{
  static const char* value()
  {
    return DataType< ::cpswarm_msgs::GetWaypoint >::value();
  }
  static const char* value(const ::cpswarm_msgs::GetWaypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CPSWARM_MSGS_MESSAGE_GETWAYPOINT_H
