// Generated by gencpp from file cpswarm_msgs/GetWaypointRequest.msg
// DO NOT EDIT!


#ifndef CPSWARM_MSGS_MESSAGE_GETWAYPOINTREQUEST_H
#define CPSWARM_MSGS_MESSAGE_GETWAYPOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace cpswarm_msgs
{
template <class ContainerAllocator>
struct GetWaypointRequest_
{
  typedef GetWaypointRequest_<ContainerAllocator> Type;

  GetWaypointRequest_()
    : position()
    , tolerance(0.0)  {
    }
  GetWaypointRequest_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , tolerance(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef double _tolerance_type;
  _tolerance_type tolerance;





  typedef boost::shared_ptr< ::cpswarm_msgs::GetWaypointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cpswarm_msgs::GetWaypointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetWaypointRequest_

typedef ::cpswarm_msgs::GetWaypointRequest_<std::allocator<void> > GetWaypointRequest;

typedef boost::shared_ptr< ::cpswarm_msgs::GetWaypointRequest > GetWaypointRequestPtr;
typedef boost::shared_ptr< ::cpswarm_msgs::GetWaypointRequest const> GetWaypointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cpswarm_msgs::GetWaypointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cpswarm_msgs::GetWaypointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cpswarm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'swarmros': ['/opt/ros/kinetic/share/swarmros/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'cpswarm_msgs': ['/home/miguel/ws/cpswarm_server/src/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/devel/.private/cpswarm_msgs/share/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/src/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/devel/.private/cpswarm_msgs/share/cpswarm_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cpswarm_msgs::GetWaypointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpswarm_msgs::GetWaypointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpswarm_msgs::GetWaypointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpswarm_msgs::GetWaypointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpswarm_msgs::GetWaypointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpswarm_msgs::GetWaypointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cpswarm_msgs::GetWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ce98ed55e579a98919101f8cee6523b";
  }

  static const char* value(const ::cpswarm_msgs::GetWaypointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ce98ed55e579a98ULL;
  static const uint64_t static_value2 = 0x919101f8cee6523bULL;
};

template<class ContainerAllocator>
struct DataType< ::cpswarm_msgs::GetWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cpswarm_msgs/GetWaypointRequest";
  }

  static const char* value(const ::cpswarm_msgs::GetWaypointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cpswarm_msgs::GetWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n\
float64 tolerance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::cpswarm_msgs::GetWaypointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cpswarm_msgs::GetWaypointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.tolerance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetWaypointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cpswarm_msgs::GetWaypointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cpswarm_msgs::GetWaypointRequest_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "tolerance: ";
    Printer<double>::stream(s, indent + "  ", v.tolerance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CPSWARM_MSGS_MESSAGE_GETWAYPOINTREQUEST_H
