// Generated by gencpp from file cpswarm_msgs/NedToEnu.msg
// DO NOT EDIT!


#ifndef CPSWARM_MSGS_MESSAGE_NEDTOENU_H
#define CPSWARM_MSGS_MESSAGE_NEDTOENU_H

#include <ros/service_traits.h>


#include <cpswarm_msgs/NedToEnuRequest.h>
#include <cpswarm_msgs/NedToEnuResponse.h>


namespace cpswarm_msgs
{

struct NedToEnu
{

typedef NedToEnuRequest Request;
typedef NedToEnuResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NedToEnu
} // namespace cpswarm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cpswarm_msgs::NedToEnu > {
  static const char* value()
  {
    return "66c5e4df326badf03ba3dcd62381cf2e";
  }

  static const char* value(const ::cpswarm_msgs::NedToEnu&) { return value(); }
};

template<>
struct DataType< ::cpswarm_msgs::NedToEnu > {
  static const char* value()
  {
    return "cpswarm_msgs/NedToEnu";
  }

  static const char* value(const ::cpswarm_msgs::NedToEnu&) { return value(); }
};


// service_traits::MD5Sum< ::cpswarm_msgs::NedToEnuRequest> should match 
// service_traits::MD5Sum< ::cpswarm_msgs::NedToEnu > 
template<>
struct MD5Sum< ::cpswarm_msgs::NedToEnuRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cpswarm_msgs::NedToEnu >::value();
  }
  static const char* value(const ::cpswarm_msgs::NedToEnuRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpswarm_msgs::NedToEnuRequest> should match 
// service_traits::DataType< ::cpswarm_msgs::NedToEnu > 
template<>
struct DataType< ::cpswarm_msgs::NedToEnuRequest>
{
  static const char* value()
  {
    return DataType< ::cpswarm_msgs::NedToEnu >::value();
  }
  static const char* value(const ::cpswarm_msgs::NedToEnuRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cpswarm_msgs::NedToEnuResponse> should match 
// service_traits::MD5Sum< ::cpswarm_msgs::NedToEnu > 
template<>
struct MD5Sum< ::cpswarm_msgs::NedToEnuResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cpswarm_msgs::NedToEnu >::value();
  }
  static const char* value(const ::cpswarm_msgs::NedToEnuResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cpswarm_msgs::NedToEnuResponse> should match 
// service_traits::DataType< ::cpswarm_msgs::NedToEnu > 
template<>
struct DataType< ::cpswarm_msgs::NedToEnuResponse>
{
  static const char* value()
  {
    return DataType< ::cpswarm_msgs::NedToEnu >::value();
  }
  static const char* value(const ::cpswarm_msgs::NedToEnuResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CPSWARM_MSGS_MESSAGE_NEDTOENU_H
