// Generated by gencpp from file cpswarm_msgs/OutOfBoundsResponse.msg
// DO NOT EDIT!


#ifndef CPSWARM_MSGS_MESSAGE_OUTOFBOUNDSRESPONSE_H
#define CPSWARM_MSGS_MESSAGE_OUTOFBOUNDSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cpswarm_msgs
{
template <class ContainerAllocator>
struct OutOfBoundsResponse_
{
  typedef OutOfBoundsResponse_<ContainerAllocator> Type;

  OutOfBoundsResponse_()
    : out(false)  {
    }
  OutOfBoundsResponse_(const ContainerAllocator& _alloc)
    : out(false)  {
  (void)_alloc;
    }



   typedef uint8_t _out_type;
  _out_type out;





  typedef boost::shared_ptr< ::cpswarm_msgs::OutOfBoundsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cpswarm_msgs::OutOfBoundsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct OutOfBoundsResponse_

typedef ::cpswarm_msgs::OutOfBoundsResponse_<std::allocator<void> > OutOfBoundsResponse;

typedef boost::shared_ptr< ::cpswarm_msgs::OutOfBoundsResponse > OutOfBoundsResponsePtr;
typedef boost::shared_ptr< ::cpswarm_msgs::OutOfBoundsResponse const> OutOfBoundsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cpswarm_msgs::OutOfBoundsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cpswarm_msgs::OutOfBoundsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cpswarm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'swarmros': ['/opt/ros/kinetic/share/swarmros/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'cpswarm_msgs': ['/home/miguel/ws/cpswarm_server/src/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/devel/.private/cpswarm_msgs/share/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/src/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/devel/.private/cpswarm_msgs/share/cpswarm_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cpswarm_msgs::OutOfBoundsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpswarm_msgs::OutOfBoundsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpswarm_msgs::OutOfBoundsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpswarm_msgs::OutOfBoundsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpswarm_msgs::OutOfBoundsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpswarm_msgs::OutOfBoundsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cpswarm_msgs::OutOfBoundsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32970d3e7822c2c952eeb697b73b10b5";
  }

  static const char* value(const ::cpswarm_msgs::OutOfBoundsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32970d3e7822c2c9ULL;
  static const uint64_t static_value2 = 0x52eeb697b73b10b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::cpswarm_msgs::OutOfBoundsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cpswarm_msgs/OutOfBoundsResponse";
  }

  static const char* value(const ::cpswarm_msgs::OutOfBoundsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cpswarm_msgs::OutOfBoundsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool out\n\
\n\
";
  }

  static const char* value(const ::cpswarm_msgs::OutOfBoundsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cpswarm_msgs::OutOfBoundsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.out);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OutOfBoundsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cpswarm_msgs::OutOfBoundsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cpswarm_msgs::OutOfBoundsResponse_<ContainerAllocator>& v)
  {
    s << indent << "out: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.out);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CPSWARM_MSGS_MESSAGE_OUTOFBOUNDSRESPONSE_H
