// Generated by gencpp from file cpswarm_msgs/StateEvent.msg
// DO NOT EDIT!


#ifndef CPSWARM_MSGS_MESSAGE_STATEEVENT_H
#define CPSWARM_MSGS_MESSAGE_STATEEVENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <swarmros/EventHeader.h>

namespace cpswarm_msgs
{
template <class ContainerAllocator>
struct StateEvent_
{
  typedef StateEvent_<ContainerAllocator> Type;

  StateEvent_()
    : header()
    , swarmio()
    , state()  {
    }
  StateEvent_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , swarmio(_alloc)
    , state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::swarmros::EventHeader_<ContainerAllocator>  _swarmio_type;
  _swarmio_type swarmio;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::cpswarm_msgs::StateEvent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cpswarm_msgs::StateEvent_<ContainerAllocator> const> ConstPtr;

}; // struct StateEvent_

typedef ::cpswarm_msgs::StateEvent_<std::allocator<void> > StateEvent;

typedef boost::shared_ptr< ::cpswarm_msgs::StateEvent > StateEventPtr;
typedef boost::shared_ptr< ::cpswarm_msgs::StateEvent const> StateEventConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cpswarm_msgs::StateEvent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cpswarm_msgs::StateEvent_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cpswarm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'swarmros': ['/opt/ros/kinetic/share/swarmros/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'cpswarm_msgs': ['/home/miguel/ws/cpswarm_server/src/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/devel/.private/cpswarm_msgs/share/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/src/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/devel/.private/cpswarm_msgs/share/cpswarm_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cpswarm_msgs::StateEvent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpswarm_msgs::StateEvent_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpswarm_msgs::StateEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpswarm_msgs::StateEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpswarm_msgs::StateEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpswarm_msgs::StateEvent_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cpswarm_msgs::StateEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a5df14620d91348b445fa85a7015e57";
  }

  static const char* value(const ::cpswarm_msgs::StateEvent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a5df14620d91348ULL;
  static const uint64_t static_value2 = 0xb445fa85a7015e57ULL;
};

template<class ContainerAllocator>
struct DataType< ::cpswarm_msgs::StateEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cpswarm_msgs/StateEvent";
  }

  static const char* value(const ::cpswarm_msgs::StateEvent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cpswarm_msgs::StateEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header       # ros header\n\
swarmros/EventHeader swarmio # cpswarm swarmio swarmros header\n\
string state                 # state of the cps\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: swarmros/EventHeader\n\
string name # Name of the event\n\
string node # UUID of the source or target node\n\
";
  }

  static const char* value(const ::cpswarm_msgs::StateEvent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cpswarm_msgs::StateEvent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.swarmio);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StateEvent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cpswarm_msgs::StateEvent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cpswarm_msgs::StateEvent_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "swarmio: ";
    s << std::endl;
    Printer< ::swarmros::EventHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.swarmio);
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CPSWARM_MSGS_MESSAGE_STATEEVENT_H
