// Generated by gencpp from file cpswarm_msgs/TrackingGoal.msg
// DO NOT EDIT!


#ifndef CPSWARM_MSGS_MESSAGE_TRACKINGGOAL_H
#define CPSWARM_MSGS_MESSAGE_TRACKINGGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cpswarm_msgs
{
template <class ContainerAllocator>
struct TrackingGoal_
{
  typedef TrackingGoal_<ContainerAllocator> Type;

  TrackingGoal_()
    : target(0)  {
    }
  TrackingGoal_(const ContainerAllocator& _alloc)
    : target(0)  {
  (void)_alloc;
    }



   typedef uint32_t _target_type;
  _target_type target;





  typedef boost::shared_ptr< ::cpswarm_msgs::TrackingGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cpswarm_msgs::TrackingGoal_<ContainerAllocator> const> ConstPtr;

}; // struct TrackingGoal_

typedef ::cpswarm_msgs::TrackingGoal_<std::allocator<void> > TrackingGoal;

typedef boost::shared_ptr< ::cpswarm_msgs::TrackingGoal > TrackingGoalPtr;
typedef boost::shared_ptr< ::cpswarm_msgs::TrackingGoal const> TrackingGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cpswarm_msgs::TrackingGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cpswarm_msgs::TrackingGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cpswarm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'swarmros': ['/opt/ros/kinetic/share/swarmros/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'cpswarm_msgs': ['/home/miguel/ws/cpswarm_server/src/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/devel/.private/cpswarm_msgs/share/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/src/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/devel/.private/cpswarm_msgs/share/cpswarm_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cpswarm_msgs::TrackingGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpswarm_msgs::TrackingGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpswarm_msgs::TrackingGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpswarm_msgs::TrackingGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpswarm_msgs::TrackingGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpswarm_msgs::TrackingGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cpswarm_msgs::TrackingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8f971e83c003dca3d6eef9786213230";
  }

  static const char* value(const ::cpswarm_msgs::TrackingGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8f971e83c003dcaULL;
  static const uint64_t static_value2 = 0x3d6eef9786213230ULL;
};

template<class ContainerAllocator>
struct DataType< ::cpswarm_msgs::TrackingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cpswarm_msgs/TrackingGoal";
  }

  static const char* value(const ::cpswarm_msgs::TrackingGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cpswarm_msgs::TrackingGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
uint32 target   # id of the target\n\
";
  }

  static const char* value(const ::cpswarm_msgs::TrackingGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cpswarm_msgs::TrackingGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackingGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cpswarm_msgs::TrackingGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cpswarm_msgs::TrackingGoal_<ContainerAllocator>& v)
  {
    s << indent << "target: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CPSWARM_MSGS_MESSAGE_TRACKINGGOAL_H
