// Generated by gencpp from file cpswarm_msgs/Vector.msg
// DO NOT EDIT!


#ifndef CPSWARM_MSGS_MESSAGE_VECTOR_H
#define CPSWARM_MSGS_MESSAGE_VECTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cpswarm_msgs
{
template <class ContainerAllocator>
struct Vector_
{
  typedef Vector_<ContainerAllocator> Type;

  Vector_()
    : magnitude(0.0)
    , direction(0.0)  {
    }
  Vector_(const ContainerAllocator& _alloc)
    : magnitude(0.0)
    , direction(0.0)  {
  (void)_alloc;
    }



   typedef float _magnitude_type;
  _magnitude_type magnitude;

   typedef float _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::cpswarm_msgs::Vector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cpswarm_msgs::Vector_<ContainerAllocator> const> ConstPtr;

}; // struct Vector_

typedef ::cpswarm_msgs::Vector_<std::allocator<void> > Vector;

typedef boost::shared_ptr< ::cpswarm_msgs::Vector > VectorPtr;
typedef boost::shared_ptr< ::cpswarm_msgs::Vector const> VectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cpswarm_msgs::Vector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cpswarm_msgs::Vector_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cpswarm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'swarmros': ['/opt/ros/kinetic/share/swarmros/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'cpswarm_msgs': ['/home/miguel/ws/cpswarm_server/src/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/devel/.private/cpswarm_msgs/share/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/src/cpswarm_msgs/msg', '/home/miguel/ws/cpswarm_server/devel/.private/cpswarm_msgs/share/cpswarm_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cpswarm_msgs::Vector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cpswarm_msgs::Vector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpswarm_msgs::Vector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cpswarm_msgs::Vector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpswarm_msgs::Vector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cpswarm_msgs::Vector_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cpswarm_msgs::Vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb4005f5e84d241c0c41a25e2094bb18";
  }

  static const char* value(const ::cpswarm_msgs::Vector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb4005f5e84d241cULL;
  static const uint64_t static_value2 = 0x0c41a25e2094bb18ULL;
};

template<class ContainerAllocator>
struct DataType< ::cpswarm_msgs::Vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cpswarm_msgs/Vector";
  }

  static const char* value(const ::cpswarm_msgs::Vector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cpswarm_msgs::Vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 magnitude # magnitude of vector\n\
float32 direction # direction of vector\n\
";
  }

  static const char* value(const ::cpswarm_msgs::Vector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cpswarm_msgs::Vector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.magnitude);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Vector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cpswarm_msgs::Vector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cpswarm_msgs::Vector_<ContainerAllocator>& v)
  {
    s << indent << "magnitude: ";
    Printer<float>::stream(s, indent + "  ", v.magnitude);
    s << indent << "direction: ";
    Printer<float>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CPSWARM_MSGS_MESSAGE_VECTOR_H
