// Auto-generated. Do not edit!

// (in-package cpswarm_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class TaskAllocationResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.winner = null;
      this.task_id = null;
      this.task_pose = null;
    }
    else {
      if (initObj.hasOwnProperty('winner')) {
        this.winner = initObj.winner
      }
      else {
        this.winner = '';
      }
      if (initObj.hasOwnProperty('task_id')) {
        this.task_id = initObj.task_id
      }
      else {
        this.task_id = 0;
      }
      if (initObj.hasOwnProperty('task_pose')) {
        this.task_pose = initObj.task_pose
      }
      else {
        this.task_pose = new geometry_msgs.msg.PoseStamped();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type TaskAllocationResult
    // Serialize message field [winner]
    bufferOffset = _serializer.string(obj.winner, buffer, bufferOffset);
    // Serialize message field [task_id]
    bufferOffset = _serializer.uint32(obj.task_id, buffer, bufferOffset);
    // Serialize message field [task_pose]
    bufferOffset = geometry_msgs.msg.PoseStamped.serialize(obj.task_pose, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type TaskAllocationResult
    let len;
    let data = new TaskAllocationResult(null);
    // Deserialize message field [winner]
    data.winner = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [task_id]
    data.task_id = _deserializer.uint32(buffer, bufferOffset);
    // Deserialize message field [task_pose]
    data.task_pose = geometry_msgs.msg.PoseStamped.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.winner.length;
    length += geometry_msgs.msg.PoseStamped.getMessageSize(object.task_pose);
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'cpswarm_msgs/TaskAllocationResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f60eadc47e6ce28a299309752f58de4b';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    string winner                       # UUID of the CPS to which the task is allocated
    uint32 task_id                      # ID of the task
    geometry_msgs/PoseStamped task_pose # Local position of the task (if assignment failed, use as input)
    
    ================================================================================
    MSG: geometry_msgs/PoseStamped
    # A Pose with reference coordinate frame and timestamp
    Header header
    Pose pose
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    # 0: no frame
    # 1: global frame
    string frame_id
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new TaskAllocationResult(null);
    if (msg.winner !== undefined) {
      resolved.winner = msg.winner;
    }
    else {
      resolved.winner = ''
    }

    if (msg.task_id !== undefined) {
      resolved.task_id = msg.task_id;
    }
    else {
      resolved.task_id = 0
    }

    if (msg.task_pose !== undefined) {
      resolved.task_pose = geometry_msgs.msg.PoseStamped.Resolve(msg.task_pose)
    }
    else {
      resolved.task_pose = new geometry_msgs.msg.PoseStamped()
    }

    return resolved;
    }
};

module.exports = TaskAllocationResult;
