; Auto-generated. Do not edit!


(cl:in-package cpswarm_msgs-msg)


;//! \htmlinclude CoverageFeedback.msg.html

(cl:defclass <CoverageFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass CoverageFeedback (<CoverageFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CoverageFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CoverageFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cpswarm_msgs-msg:<CoverageFeedback> is deprecated: use cpswarm_msgs-msg:CoverageFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CoverageFeedback>) ostream)
  "Serializes a message object of type '<CoverageFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CoverageFeedback>) istream)
  "Deserializes a message object of type '<CoverageFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CoverageFeedback>)))
  "Returns string type for a message object of type '<CoverageFeedback>"
  "cpswarm_msgs/CoverageFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CoverageFeedback)))
  "Returns string type for a message object of type 'CoverageFeedback"
  "cpswarm_msgs/CoverageFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CoverageFeedback>)))
  "Returns md5sum for a message object of type '<CoverageFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CoverageFeedback)))
  "Returns md5sum for a message object of type 'CoverageFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CoverageFeedback>)))
  "Returns full string definition for message of type '<CoverageFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CoverageFeedback)))
  "Returns full string definition for message of type 'CoverageFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CoverageFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CoverageFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CoverageFeedback
))
