; Auto-generated. Do not edit!


(cl:in-package cpswarm_msgs-msg)


;//! \htmlinclude TargetFeedback.msg.html

(cl:defclass <TargetFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TargetFeedback (<TargetFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TargetFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TargetFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cpswarm_msgs-msg:<TargetFeedback> is deprecated: use cpswarm_msgs-msg:TargetFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TargetFeedback>) ostream)
  "Serializes a message object of type '<TargetFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TargetFeedback>) istream)
  "Deserializes a message object of type '<TargetFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TargetFeedback>)))
  "Returns string type for a message object of type '<TargetFeedback>"
  "cpswarm_msgs/TargetFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TargetFeedback)))
  "Returns string type for a message object of type 'TargetFeedback"
  "cpswarm_msgs/TargetFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TargetFeedback>)))
  "Returns md5sum for a message object of type '<TargetFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TargetFeedback)))
  "Returns md5sum for a message object of type 'TargetFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TargetFeedback>)))
  "Returns full string definition for message of type '<TargetFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the feeeback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TargetFeedback)))
  "Returns full string definition for message of type 'TargetFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the feeeback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TargetFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TargetFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TargetFeedback
))
