; Auto-generated. Do not edit!


(cl:in-package cpswarm_msgs-msg)


;//! \htmlinclude TaskAllocationFeedback.msg.html

(cl:defclass <TaskAllocationFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TaskAllocationFeedback (<TaskAllocationFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TaskAllocationFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TaskAllocationFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cpswarm_msgs-msg:<TaskAllocationFeedback> is deprecated: use cpswarm_msgs-msg:TaskAllocationFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TaskAllocationFeedback>) ostream)
  "Serializes a message object of type '<TaskAllocationFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TaskAllocationFeedback>) istream)
  "Deserializes a message object of type '<TaskAllocationFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TaskAllocationFeedback>)))
  "Returns string type for a message object of type '<TaskAllocationFeedback>"
  "cpswarm_msgs/TaskAllocationFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TaskAllocationFeedback)))
  "Returns string type for a message object of type 'TaskAllocationFeedback"
  "cpswarm_msgs/TaskAllocationFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TaskAllocationFeedback>)))
  "Returns md5sum for a message object of type '<TaskAllocationFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TaskAllocationFeedback)))
  "Returns md5sum for a message object of type 'TaskAllocationFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TaskAllocationFeedback>)))
  "Returns full string definition for message of type '<TaskAllocationFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the feeeback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TaskAllocationFeedback)))
  "Returns full string definition for message of type 'TaskAllocationFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the feeeback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TaskAllocationFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TaskAllocationFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TaskAllocationFeedback
))
