; Auto-generated. Do not edit!


(cl:in-package cpswarm_msgs-msg)


;//! \htmlinclude TrackingGoal.msg.html

(cl:defclass <TrackingGoal> (roslisp-msg-protocol:ros-message)
  ((target
    :reader target
    :initarg :target
    :type cl:integer
    :initform 0))
)

(cl:defclass TrackingGoal (<TrackingGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TrackingGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TrackingGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cpswarm_msgs-msg:<TrackingGoal> is deprecated: use cpswarm_msgs-msg:TrackingGoal instead.")))

(cl:ensure-generic-function 'target-val :lambda-list '(m))
(cl:defmethod target-val ((m <TrackingGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cpswarm_msgs-msg:target-val is deprecated.  Use cpswarm_msgs-msg:target instead.")
  (target m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TrackingGoal>) ostream)
  "Serializes a message object of type '<TrackingGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'target)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'target)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'target)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'target)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TrackingGoal>) istream)
  "Deserializes a message object of type '<TrackingGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'target)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'target)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'target)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'target)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TrackingGoal>)))
  "Returns string type for a message object of type '<TrackingGoal>"
  "cpswarm_msgs/TrackingGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TrackingGoal)))
  "Returns string type for a message object of type 'TrackingGoal"
  "cpswarm_msgs/TrackingGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TrackingGoal>)))
  "Returns md5sum for a message object of type '<TrackingGoal>"
  "e8f971e83c003dca3d6eef9786213230")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TrackingGoal)))
  "Returns md5sum for a message object of type 'TrackingGoal"
  "e8f971e83c003dca3d6eef9786213230")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TrackingGoal>)))
  "Returns full string definition for message of type '<TrackingGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 target   # id of the target~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TrackingGoal)))
  "Returns full string definition for message of type 'TrackingGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 target   # id of the target~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TrackingGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TrackingGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'TrackingGoal
    (cl:cons ':target (target msg))
))
